export const statuses =  [
    { id: 1, status: "Fail"},
    { id: 2, status: "Fail"},
    { id: 3, status: "Fail"},
    { id: 4, status: "Fail"},
    { id: 5, status: "Fail"},
    { id: 6, status: "Fail"},
    { id: 7, status: "Fail"},
    { id: 8, status: "Fail"},
    { id: 9, status: "Fail"},
    { id: 10, status: "Fail"},
    { id: 11, status: "Fail"},
    { id: 12, status: "Pass"},
    { id: 13, status: "Pass"},
    { id: 14, status: "Pass"},
    { id: 15, status: "Pass"},
    { id: 16, status: "Pass"},
    { id: 17, status: "Pass"},
    { id: 18, status: "Pass"},
    { id: 19, status: "Pass"},
    { id: 20, status: "Pass"},
    { id: 21, status: "Pass"},
    { id: 22, status: "Pass"},
    { id: 23, status: "Pass"},
    { id: 24, status: "Pass"},
    { id: 25, status: "Pass"},
    { id: 26, status: "Pass"},
    { id: 27, status: "Pass"},
    { id: 28, status: "Warn"},
    { id: 29, status: "Warn"},
    { id: 30, status: "Warn"},
    { id: 31, status: "Warn"},
    { id: 32, status: "Warn"},
    { id: 33, status: "Warn"},
    { id: 34, status: "Warn"},
    { id: 35, status: "Warn"},
    { id: 36, status: "Warn"},
    { id: 37, status: "Warn"}
];

export const states = {
    "Texas": { capital: "Austin", region: "South", abbreviation: "TX", timeStamp: new Date().toString()},
    "Wisconsin": { capital: "Madison", region: "Midwest", abbreviation: "WI", timeStamp: new Date().toString()},
    "Oregon": { capital: "Salem", region: "Northwest", abbreviation: "OR", timeStamp: new Date().toString()},
    "California": { capital: "Sacramento", region: "West", abbreviation: "CA", timeStamp: new Date().toString()},
    "Virginia": { capital: "Richmond", region: "East", abbreviation: "VA", timeStamp: new Date().toString()},
};